bcp ^
    boost/asio.hpp ^
    boost/container/flat_map.hpp ^
    boost/container/flat_set.hpp ^
    boost/container/small_vector.hpp ^
    boost/container/static_vector.hpp ^
    boost/crc.hpp ^
    boost/date_time/posix_time/posix_time.hpp ^
    boost/icl/interval_map.hpp ^
    boost/optional.hpp ^
    boost/pool/ ^
    boost/range/algorithm/ ^
    boost/range/algorithm_ext/ ^
    boost/system/error_code.hpp ^
    boost/system/system_error.hpp ^
    --boost="%1" .
